Repository recodehive/recode-website, pull requests merged in 2025-05, with the labels that each got.

#34 Fix: Course link navigation blocked by ParticlesComponent
  src/components/particle.tsx
Labels: area:production-image

#42 Feature/podcast
  docusaurus.config.ts
  src/pages/podcasts/details.tsx
  src/pages/podcasts/index.css
  src/pages/podcasts/index.tsx
Labels: area:dev-env

#53 Feature/broadcast
  docusaurus.config.ts
  src/pages/broadcasts/details.tsx
  src/pages/broadcasts/index.css
  src/pages/broadcasts/index.tsx
  src/pages/broadcasts/video.css
Labels: area:UI

#64 Enhance sponsor page layout with tabbed navigation and improved styling
  src/pages/our-sponsors/Sponsors.css
  src/pages/our-sponsors/index.tsx
Labels: area:db
