Repository recodehive/recode-website, pull requests merged in 2025-09, with the labels that each got.

#461 Added docs for all types of SQL joins
  docs/sql/SQL-joins/assets/cross-join.gif
  docs/sql/SQL-joins/assets/full-outer-join.gif
  docs/sql/SQL-joins/assets/inner-join.png
  docs/sql/SQL-joins/assets/intro-sql-joins.png
  docs/sql/SQL-joins/assets/left-outer-join.png
  docs/sql/SQL-joins/assets/right-join.gif
  docs/sql/SQL-joins/assets/self-join.png
  docs/sql/SQL-joins/cross-join.md
  docs/sql/SQL-joins/full-outer-join.md
  docs/sql/SQL-joins/inner-join.md
  docs/sql/SQL-joins/intro-sql-joins.md
  docs/sql/SQL-joins/left-join.md
  docs/sql/SQL-joins/right-join.md
  docs/sql/SQL-joins/self-join.md
  sidebars.ts
Labels: under review

#482 Added the rolling numbers effect
  src/theme/Footer/Layout/Counter.tsx
  src/theme/Footer/Layout/index.tsx
Labels: gssoc25, level 2, under review

#484 Fix design issue , icons visiblity for small devices
  src/css/custom.css
Labels: gssoc25, level 2

#489 Improve UI get_started page
  src/pages/get-started/index.tsx
  src/pages/get-started/styles.module.css
Labels: gssoc25, level 2

#493 Feature/liveactivity
  package.json
  src/components/FloatingContributors/FloatingContributors.css
  src/components/FloatingContributors/README.md
  src/components/FloatingContributors/index.tsx
Labels: under review

#495 Add references section to README with GitHub profiles
  src/components/FloatingContributors/README.md
Labels: documentation

#447 Redesigned Hero of Main page
  src/components/FloatingContributors/FloatingContributors.css
  src/components/header/header.css
Labels: under review

#503 Broadcast Page UI Changed
  src/pages/broadcasts/index.css
  src/pages/broadcasts/index.tsx
  src/pages/broadcasts/video.css
Labels: gssoc25, level 3

#506 Bug/toaster
  src/components/FloatingContributors/FloatingContributors.css
  src/components/FloatingContributors/index.tsx
  src/components/blogCarousel/blogCarousel.css
Labels: enhancement

#510 Fix testimonial responsiveness in courses page
  src/pages/courses/courses.css
Labels: gssoc25, level 2

#522 Implement pagination with ellipsis for improved navigation in leaderboard
  src/components/dashboard/LeaderBoard/leaderboard.css
  src/components/dashboard/LeaderBoard/leaderboard.tsx
Labels: level 1, Ready for Merge

#515 Blog post about n8n AI Workflow
  blog/n8n-workflow-automation/images/n8n-architecture-example.png
  blog/n8n-workflow-automation/index.md
  src/database/blogs/index.tsx
  src/pages/blogs/index.tsx
  static/img/blogs/n8n-logo.png
Labels: gssoc25, level 3, Ready for Merge

#524 Optimize the stats load with the use of caching
  src/lib/statsProvider.tsx
Labels: gssoc25, level 2

#525 Fixed the naming and description on showcase page
  src/data/userData.tsx
Labels: gssoc25, level 1

#534 Add Toast in the newsletter on subscribe
  src/theme/Footer/Layout/enhanced-footer.css
  src/theme/Footer/Layout/index.tsx
Labels: gssoc25, level 2

#537 Removed the public repo stat card
  src/pages/dashboard/index.tsx
Labels: gssoc25, level 1

#541 Refine pull request template for better guidance
  .github/pull_request_template.md
Labels: gssoc25, level 2

#545 Fix : Text Visibility in light mode on Contact page
  src/pages/contact-us/index.tsx
Labels: gssoc25, level 2

#553 Added link to the testimonies card
  src/components/testimonials/TestimonialCard.tsx
  src/components/testimonials/TestimonialCarousel.tsx
Labels: gssoc25, level 2

#556 Fixed the docs landing page issue
  docs/index.md
  sidebars.ts
Labels: area:API, good first issue, under review

#559 Update button styles for improved visibility and interaction
  src/pages/careers/index.tsx
Labels: gssoc25, level 2

#560 add topmate close functionality
  src/components/topmate/TopMateCard.tsx
  src/components/topmate/TopMateSection.tsx
  src/pages/index.tsx
Labels: gssoc25, level 2

#570 Fixed the text visibility on button
  src/pages/get-started/index.tsx
  src/pages/terms-service/index.tsx
Labels: gssoc25, level 2

#571 Fixed the link on Documentation card
  src/pages/community/index.tsx
Labels: gssoc25, level 2

#573 Added links in the community
  src/pages/community/index.tsx
Labels: gssoc25, level 2

#575 Enhance community page with dropdown details for contribution section…
  src/pages/community/community.css
  src/pages/community/index.tsx
Labels: kind:bug, enhancement, under review

#584 Added PR's to the leaderboard
  src/components/dashboard/LeaderBoard/PRListModal.tsx
  src/components/dashboard/LeaderBoard/leaderboard.css
  src/components/dashboard/LeaderBoard/leaderboard.tsx
  src/components/dashboard/LeaderBoard/mockData.ts
  src/lib/statsProvider.tsx
Labels: gssoc25, level 2, Ready for Merge

#590 fix: enable dark mode support on Careers page
  package.json
  src/pages/careers/index.tsx
  tsconfig.json
Labels: kind:bug, gssoc25, level 1, Ready for Merge

#592 Fixed Open Positions button redirection to careers section (#578)
  src/pages/careers/index.tsx
Labels: kind:bug, gssoc25, level 2, Ready for Merge

#593 Fixed learn about our culture button redirection to our culture (#579)
  src/pages/careers/index.tsx
Labels: kind:bug, gssoc25, level 2, Ready for Merge

#595 add share functionality
  src/pages/podcasts/index.tsx
Labels: gssoc25, level 2, Ready for Merge

#598 use X icon
  src/pages/our-sponsors/SponsorCard/index.tsx
Labels: gssoc25, level 2, Ready for Merge

#602 Added Workflow for Sync in issue and PR
  .github/workflows/pr-issue-sync.yml
Labels: enhancement, gssoc25, level 2

#605 fixed the filters PR Modal
  src/components/dashboard/LeaderBoard/PRListModal.tsx
  src/components/dashboard/LeaderBoard/leaderboard.tsx
  src/lib/statsProvider.tsx
Labels: gssoc25, level 2

#609 Added workflow for auto labels on PR and Issues
  .github/workflows/autolabler.yml
  .github/workflows/pr-issue-sync.yml
Labels: gssoc25, level 2

#613 Updated the title on homepage
  src/components/header/header.css
Labels: gssoc25, level 1, recode

#616 Added subpage for Welcome
  docs/getting_started.md
  sidebars.ts
Labels: gssoc25, level 1, recode
