Repository recodehive/recode-website, pull requests merged in 2025-08, with the labels that each got.

#257 Footer UI Fix: Replace Twitter with X
  package.json
  src/theme/Footer/index.tsx
Labels: gssoc25, level 1

#260 Enhanced ui for blog page
  src/css/custom.css
  src/pages/blogs/blogs-new.css
  src/pages/blogs/blogs.css
  src/pages/blogs/index.tsx
Labels: gssoc25, level 3

#266 [Fix][Docs]: Improved button and added image alt
  docs/Google-Student-Ambassador/part-1-getting-started/index.mdx
  docs/Google-Student-Ambassador/part-2-application-process/index.mdx
  docs/Google-Student-Ambassador/part-3-eligibility/index.mdx
  docs/python/python-variables.md
Labels: gssoc25, level 2

#271 Fixed the darktheme related issue.
  src/components/Roadmap/Roadmap.css
  src/components/TeamProfileCards/teamcards.css
  src/css/custom.css
  src/pages/badges/github-badges.module.css
  src/pages/badges/github-badges.tsx
  src/pages/blogs/blogs.css
  src/pages/broadcasts/index.css
  src/pages/broadcasts/video.css
  src/pages/careers/index.tsx
  src/pages/community/community.css
  src/pages/courses/courses.css
  src/pages/courses/index.tsx
  src/pages/get-started/index.tsx
  src/pages/get-started/styles.module.css
  src/pages/our-sponsors/Sponsors.css
  src/pages/podcasts/index.css
  src/pages/showcase/styles.module.css
  src/theme/Footer/Layout/enhanced-footer.css
Labels: gssoc25, level 3

#277 gssoc/fixed mis-alignment of icons on sidebar closing
  src/pages/dashboard/dashboard.css
Labels: area:db, area:dev-env, gssoc25, level 2

#292 Added Github-icon for smaller screens, proper spacing and padding for right-navitems
  docs/python/python_operators.md
  src/components/ui/NavbarFirebaseAuthGithub.tsx
  src/css/custom.css
  static/remove-mobile-theme-toggle.js
Labels: gssoc25, level 2

#294 Replaced HeaderImage/ Vanilla with toaster
  src/components/FloatingContributors/FloatingContributors.css
  src/components/FloatingContributors/index.tsx
  src/components/header/header.css
  src/components/header/header.tsx
  src/pages/index.tsx
Labels: gssoc25, level 2

#307 Updated Footer reducing unnecessary spacing
  docs/python/python_operators.md
  src/components/FloatingContributors/FloatingContributors.css
  src/components/FloatingContributors/index.tsx
  src/components/header/header.css
  src/components/header/header.tsx
  src/pages/index.tsx
  src/theme/Footer/Layout/enhanced-footer.css
  src/theme/Footer/Layout/index.tsx
Labels: gssoc25, level 2

#314 updated the github doc intro with typo corrections and grammatical improvements
  docs/GitHub/intro-github.md
Labels: gssoc25, level 1

#315 Replaced navibar and dashboard emojis with Professional Icons
  docusaurus.config.ts
  src/components/CustomSidebar.module.css
  src/components/CustomSidebar.tsx
  src/components/navbar/NavbarIcon.tsx
  src/components/navbar/NavbarIconInjector.tsx
  src/css/custom.css
  src/pages/dashboard/dashboard.css
  src/pages/dashboard/index.tsx
  src/theme/Navbar/index.tsx
  src/theme/NavbarItem.tsx
Labels: gssoc25, level 3

#316 Fix Google Analytics issue
  docusaurus.config.ts
  static/gtag-init.js
Labels: area:API

#318 feat: Behavioural Interview Prep page with structured content and UI
  src/css/custom.css
  src/pages/interview-prep/index.tsx
  static/img/Behavioural_Interviews1.png
  static/img/Behavioural_Interviews2.png
  static/img/Behavioural_Interviews3.png
Labels: gssoc25, level 2

#332 Create grouping-data.md
  docs/sql/SQL-basics/grouping-data.md
Labels: area:API

#333 Feat: UI - Overview Tab
  src/css/custom.css
  src/pages/interview-prep/index.tsx
Labels: gssoc25, level 3

#344 Added sidbar for giveaway page.
  docusaurus.config.ts
  package.json
  src/css/custom.css
  src/pages/dashboard/dashboard.css
  src/pages/dashboard/giveaway/index.tsx
  src/pages/dashboard/index.tsx
Labels: gssoc25, level 2

#346 sql datatypes documentation added
  docs/sql/SQL-basics/assets/31-datatypes.png
  docs/sql/SQL-basics/datatypes.md
Labels: gssoc25, level 1

#360 Removed < /> from all .md files of Technical & Nextjs in docs
  docs/Nextjs/git-commands.md
  docs/Nextjs/intro-github.md
  docs/Nextjs/setup-environment.md
  docs/Technical/intro-github.md
Labels: gssoc25, level 1

#362 Enhanced Docs Sidebar
  docusaurus.config.ts
  sidebars.ts
  src/components/CustomSidebar.module.css
  src/components/CustomSidebar.tsx
  src/css/custom.css
  src/pages/get-started/index.tsx
  src/theme/DocSidebar/Desktop/index.tsx
  src/theme/DocSidebar/Desktop/styles.module.css
  src/theme/DocSidebarItem/Category/index.tsx
  src/theme/DocSidebarItem/Category/styles.module.css
  src/theme/DocSidebarItem/Html/index.tsx
  src/theme/DocSidebarItem/Html/styles.module.css
  src/theme/DocSidebarItem/Link/index.tsx
  src/theme/DocSidebarItem/Link/styles.module.css
  src/theme/DocSidebarItem/index.tsx
  src/theme/DocSidebarItem/types.ts
  src/theme/DocSidebarItems/index.tsx
  src/theme/DocSidebarItems/styles.module.css
Labels: gssoc25, level 3

#365 primary key , foreign key , constraints , sql documentation added
  docs/sql/SQL-basics/assets/32-primary-foreign-key-example.png
  docs/sql/SQL-basics/constraints.md
  docs/sql/SQL-basics/primary-key-foreign-key.md
Labels: gssoc25, level 1

#366 Fixed navbar and theme bugs
  docusaurus.config.ts
  src/components/navbar/NavbarIcon.tsx
  src/components/navbar/NavbarIconInjector.tsx
  src/components/navbar/docs.tsx
  src/components/ui/FirebaseAuthGithub.tsx
  src/components/ui/NavbarFirebaseAuthGithub.tsx
  src/constants/navbarConfig.ts
  src/css/custom.css
  src/theme/ColorModeToggle/index.tsx
  src/theme/Navbar/Content/index.tsx
  src/theme/NavbarItem.tsx
  src/theme/Root.tsx
  src/utils/navbarUtils.ts
  static/instant-theme.js
  static/theme-init.js
Labels: gssoc25, level 2

#397 ✨ Edited blogs-new.css with search bar fixes
  src/database/blogs/index.tsx
  src/pages/blogs/blogs-new.css
Labels: gssoc25, level 2

#402 updated leaderboard in giveaway page
  src/pages/dashboard/giveaway/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/leaderboard-page.css
Labels: gssoc25, level 3

#404 Updated Blog cards in home page
  blog/Spark-Architecture/index.md
  blog/spark-architecture/images/spark.png
  blog/spark-architecture/index.md
  src/components/blogCarousel/blogCard.tsx
  src/components/blogCarousel/blogCarousel.css
  src/components/blogCarousel/blogCarousel.tsx
  src/css/custom.css
  src/database/blogs/index.tsx
  src/pages/index.tsx
  src/utils/authors.ts
Labels: gssoc25, level 3

#405 Update the-inequality-operator.md
  docs/sql/SQL-basics/the-inequality-operator.md
Labels: gssoc25, level 2

#415 updated the design of the podcasts page
  src/pages/podcasts/details.css
  src/pages/podcasts/details.tsx
  src/pages/podcasts/index.css
  src/pages/podcasts/index.tsx
Labels: gssoc25, level 2

#417 added loops page in docs
  docs/python/python-loops.md
Labels: gssoc25, level 1

#428 fix contribution guideline link , Fix logo visibility
  README.md
Labels: gssoc25, level 2

#430 Added non rendered files
  sidebars.ts
Labels: gssoc25, level 2

#432 Fixed Community Page Layout
  src/pages/community/community.css
Labels: gssoc25, level 2

#456 Nextjs route fix
  docusaurus.config.ts
Labels: gssoc25, level 1
