Repository recodehive/recode-website, pull requests merged in 2025-07, with the labels that each got.

#197 Documentation Add CODE OF CONDUCT for GSSoC'25
  CODE_OF_CONDUCT.md
Labels: gssoc25, level 1

#210 Fix: Dark Mode Compatibility for Homepage Section
  sidebarsCommunity.js
  src/components/blogCarousel/blogCard.tsx
  src/components/blogCarousel/blogCarousel.tsx
  src/components/faqs/faqs.tsx
  src/components/header/header.css
  src/components/header/header.tsx
  src/components/ourProjects.tsx
  src/components/testimonials/TestimonialCard.tsx
  src/components/topmate/TopMateCard.tsx
  src/components/topmate/TopMateSection.tsx
  src/css/custom.css
  src/pages/index.tsx
  src/pages/showcase/index.tsx
Labels: gssoc25, level 3

#223 Rename Account Center
  src/theme/Footer/index.tsx
Labels: gssoc25, level 1

#219 Add Giveaway Page with Timer & Leaderboard
  package.json
  src/pages/dashboard/giveaway/index.tsx
  src/pages/dashboard/index.tsx
  tsconfig.json
Labels: gssoc25, level 3

#230 Add Professional, Elegant Newsletter Popup with Scroll Trigger
  src/components/NewsLetterPopup.tsx
  src/theme/Layout.tsx
Labels: area:backend-sql, gssoc25, level 2
