Repository recodehive/recode-website, pull requests merged in 2025-06, with the labels that each got.

#82 Feature/getstarted
  blog/google-deepmind/index.md
  src/components/StatsSection/index.tsx
  src/components/StatsSection/styles.module.css
  src/components/header/header.tsx
  src/pages/get-started/index.tsx
  src/pages/get-started/styles.module.css
Labels: area:backend-sql

#88 docs: Created full tutorial on Python Variables including scope, memory, and dynamic typing
  docs/python/_category_.json
  docs/python/assets/data-type.png
  docs/python/python-variables.md
Labels: area:db

#107 feat: add @vercel/analytics dependency and implement analytics in Root component
  package.json
  src/theme/Root.tsx
Labels: area:API, area:backend-sql

#137 docs: add detailed Python Tuples chapter
  docs/python/python-list.md
  docs/python/python-tuple.md
  docs/python/setup-environment.md
Labels: area:dev-env
