Repository recodehive/recode-website, pull requests merged in 2025-10, with the labels that each got.

#639 Fix indentation in PR issue sync workflow
  .github/workflows/pr-issue-sync.yml
Labels: gssoc25, level 1, recode, hacktoberfest-accepted

#661 Changes in dockerfiles and node version
  Dockerfile
  README.md
  docker-compose.yml
  package.json
Labels: gssoc25, level 2, recode

#667 Updated the PR Modal as per changes in Leaderboard
  src/components/dashboard/LeaderBoard/PRListModal.tsx
  src/lib/statsProvider.tsx
Labels: gssoc25, level 3, recode, hacktoberfest-accepted

#683 Add Documentation: Object-Oriented Programming (OOPs) in Python
  docs/python/python-oops.md
Labels: level 1, recode, hacktoberfest-accepted

#585 Update contribution links to include public view and invitation
  docusaurus.config.ts
  package.json
  src/pages/community/index.tsx
Labels: gssoc25, level 1, Ready for Merge, recode, hacktoberfest-accepted

#662 fix(docs):
  README.md
  docusaurus.config.ts
  package.json
Labels: level 1, recode, hacktoberfest-accepted

#679 add topic - OOPs for python
  docs/python/python_oops.md
  docusaurus.config.ts
Labels: gssoc25, level 1, recode, hacktoberfest-accepted

#698 Document link changes
  docs/Google-Student-Ambassador/part-2-application-process/index.mdx
  docs/Google-Student-Ambassador/part-3-eligibility/index.mdx
  docs/Google-Student-Ambassador/part-4-gemini-pro/index.mdx
Labels: level 1, recode, hacktoberfest-accepted

#705 docs: add new chapter on File Input and Output (I/O) in Python
  docs/python/python-io.md
  docs/python/setup-environment.md
Labels: level 1, recode, hacktoberfest-accepted

#711 Add Practice Questions to Conditional Statements in Python Documentation
  docs/python/conditional-statements-python.md
Labels: documentation, level 1, Ready for Merge, recode, hacktoberfest-accepted

#715 Github documentation changes
  docs/GitHub/setup-environment/assets/5-github-auth.png
  docs/GitHub/setup-environment/setup-environment.md
Labels: level 1, Ready for Merge, recode, hacktoberfest-accepted

#717 Add hacktoberfest Label for Auto labels assignment
  .github/workflows/autolabler.yml
Labels: level 1, recode, hacktoberfest-accepted

#719 Fix: Home icon alignment with text in Docs Breadcrumbs
  src/css/custom.css
Labels: level 1, recode, hacktoberfest-accepted

#726 chore: bind Docusaurus dev server to 0.0.0.0 for cross-platform Docker
  docker-compose.yml
Labels: level 1, recode, hacktoberfest-accepted

#727 chore: remove obsolete version field from docker-compose.yml
  docker-compose.yml
Labels: level 1, recode, hacktoberfest-accepted

#729 doc: Add Practice Questions Section to Loops in Python Documentation
  docs/python/python-loops.md
Labels: documentation, level 1, Ready for Merge, recode, hacktoberfest-accepted

#733 working search btn
  src/pages/podcasts/index.tsx
Labels: level 1, recode, hacktoberfest-accepted

#737 docs: fix typo in README ('Prerequesites' → 'Prerequisites')
  README.md
Labels: level 1, recode, hacktoberfest-accepted

#751 Fixed typo in 'CLone Repository'
  docs/GitHub/GitHub-basics/how-to-clone-repo.md
Labels: level 1, recode, hacktoberfest-accepted

#760 Unify footer across light/dark
  src/theme/Footer/Layout/enhanced-footer.css
Labels: level 1, recode, hacktoberfest-accepted

#763 fix: remove rounded corners background projects section
  src/components/ourProjects.tsx
Labels: level 1, recode, hacktoberfest-accepted

#774 docs: remove redundant 'npm i' from setup instructions
  community/contributing-guidelines.md
Labels: level 1, recode, hacktoberfest-accepted

#779 Update first-opensource-code.md
  docs/GitHub/GitHub-basics/first-opensource-code.md
Labels: level 1, recode, hacktoberfest-accepted

#792 style/docs: unify 'recode hive' branding and update contributing guidelines
  CODE_OF_CONDUCT.md
  Documentation.md
  LICENSE
  README.md
  blog/authors.yml
  blog/google-deepmind/index.md
  community/contributing-guidelines.md
  community/index.md
  community/our-documentation.md
  community/understand-lint-checks.md
  docker-setup.md
  docs/index.md
  docusaurus.config.ts
  src/components/Community/index.tsx
  src/components/NewsLetterPopup.tsx
  src/components/dashboard/LeaderBoard/leaderboard.tsx
  src/components/faqs/faqs.tsx
  src/components/header.tsx
  src/components/header/header.tsx
  src/pages/License/index.tsx
  src/pages/badges/github-badges.tsx
  src/pages/blogs/blogs-new.css
  src/pages/blogs/index.tsx
  src/pages/careers/index.tsx
  src/pages/community/index.tsx
  src/pages/contact-us/index.tsx
  src/pages/dashboard/giveaway/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/get-started/index.tsx
  src/pages/index.tsx
  src/pages/interview-prep/BehavioralTab.tsx
  src/pages/interview-prep/index.tsx
  src/pages/privacy-policy/index.tsx
  src/pages/showcase/index.tsx
  src/services/githubService.ts
  src/utils/authors.ts
Labels: level 1, recode, hacktoberfest-accepted

#793 chore/docs: remove outdated simulated "Last updated" line
  community/index.md
Labels: level 1, recode, hacktoberfest-accepted

#798 Improve search icon visibility in dark mode
  src/pages/blogs/blogs-new.css
  src/pages/blogs/index.tsx
Labels: level 1, recode, hacktoberfest-accepted

#808 Updated details on sponsors tab
  src/database/sponsors/index.tsx
Labels: gssoc25, level 1, recode, hacktoberfest-accepted

#810 docs: add Tech Stack and reformat README, update naming consistency (Hive → recode hive)
  README.md
  src/components/topmate/TopMateSection.tsx
  src/pages/community/index.tsx
  src/pages/showcase/index.tsx
Labels: level 1, recode, hacktoberfest-accepted

#817 Feature/add merch store
  .env.example
  docusaurus.config.ts
  src/components/merch/FilterBar.css
  src/components/merch/FilterBar.tsx
  src/components/merch/ProductCard.css
  src/components/merch/ProductCard.tsx
  src/components/merch/ProductGrid.css
  src/components/merch/ProductGrid.tsx
  src/components/merch/ShoppingCart.css
  src/components/merch/ShoppingCart.tsx
  src/lib/shopify.ts
  src/pages/merch/index.tsx
  src/pages/merch/merch.css
  static/img/merch/bag.jpeg
  static/img/merch/cap.jpeg
  static/img/merch/hoodie.jpeg
  static/img/merch/hoodie_2.jpeg
  static/img/merch/mug.jpeg
  static/img/merch/sticker.jpeg
  static/img/merch/tshirt.jpeg
  static/img/merch/tshirt_2.jpeg
Labels: level 1, recode, hacktoberfest-accepted

#818 docs: update linting guide for TypeScript + React
  community/understand-lint-checks.md
Labels: level 1, recode, hacktoberfest-accepted

#820 fix(Comment Section): Sync theme with site color mode
  src/components/blogCarousel/blogCard.tsx
  src/components/discussions/DiscussionCard.tsx
  src/components/giscus.tsx
Labels: level 1, recode, hacktoberfest-accepted

#823 docs: update contributing-guidelines
  README.md
  community/contributing-guidelines.md
  community/understand-lint-checks.md
Labels: don't-merge, level 1, recode, hacktoberfest-accepted

#846 feat: add VS Code workspace settings for consistent editor setup
  .vscode/extensions.json
  .vscode/settings.json
Labels: level 1, recode, hacktoberfest-accepted

#852 fixed the contact-us page bug
  src/pages/contact-us/index.css
Labels: level 1, recode, hacktoberfest-accepted

#856 Fix: Pagination buttons alignment on small screens in Contributors Leaderboard
  src/components/dashboard/LeaderBoard/leaderboard.css
Labels: level 1, recode, hacktoberfest-accepted

#859 Fix the keywords Description on Techincal Section in Docs
  docs/Technical/intro-github.md
Labels: gssoc25, level 1, recode, hacktoberfest-accepted
